#Application configurations
server:
  port: 9000
spring:
  application:
    name: gate-way

#Eureka config
eureka:
  client:
    serviceUrl:
      fetchRegistry: true
      defaultZone: http://localhost:8761/eureka
    register-with-eureka: true

okta:
  oauth2:
    issuer: https://dev-5360644.okta.com/oauth2/default
    client-id: 0oa1hbh6cs8RB1G3g5d7
    client-secret: 7X5QC1Ktu7xyPg60fVJA5wBovpxYkvYvvzgn5mb8