#Application configurations
server:
  port: 9000
spring:
  application:
    name: gate-way
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/users/**
        - id: wallet-service
          uri: lb://WALLET-SERVICE
          predicates:
            - Path=/wallets/**

#Eureka config
eureka:
  client:
    serviceUrl:
      fetchRegistry: true
      defaultZone: http://localhost:8761/eureka
    register-with-eureka: true
