#Application config
server:
  port: 8090
spring:
  application:
    name: wallet-service
  datasource:
    url: jdbc:mysql://localhost:3306/wallets_data?useSSL=false&createDatabaseIfNotExist=true&useUnicode=yes&characterEncoding=UTF-8
    username: root
    password: admin
    driverClassName: com.mysql.jdbc.Driver

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update

#Eureka config
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka