#Application config
server:
  port: 8761
spring:
  application:
    name: service-discovery

#Eureka server config
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
  instance:
    prefer-ip-address: true